Tests fix after InViewportMixin was removed
SergeAstapov/ember-in-viewport pull request #5
Opened 2021-12-02 13:57 UTC by sergeykers

1. my-component.js: transformed to class; switched from using InViewportMixin to InViewportService; removed unused properties
2. app.css: top: 0 added to fix failed test issue when using browser window
3. my-component.hbs: template created
4. in-viewport-test.js: InViewportMixin test removed
5. viewport-config.js, my-component-test.js, README.md: removed unused properties (were used in deleted mixin)
6. integration-test.js: added waitFor() for time to rendering changes
7. index.hbs: removed test of a deleted property
8. application.hbs: two links on one page made one

2021-12-03 12:45 UTC, sergeykers commented
@SergeAstapov, do you know, why https://github.com/SergeAstapov/ember-in-viewport/blob/master/addon/-private/raf-admin.js is called "mixin" in the comment at the top? Should it be called that way?

2021-12-07 04:11 UTC, SergeAstapov commented
> @SergeAstapov, do you know, why https://github.com/SergeAstapov/ember-in-viewport/blob/master/addon/-private/raf-admin.js is called "mixin" in the comment at the top? Should it be called that way?

I think just some remnants of previous changes in the codebase and potentially some copy-paste so we should be able to safely delete replace word "mixin" with "class"

2021-12-07 04:13 UTC, SergeAstapov commented
@sergeykers there are changes in `package-lock.json` but no changes in `package.json` - let's revert that file to avoid issues.

As it has `"lockfileVersion": 1`, you need to make sure you use npm < 7

2021-12-07 04:19 UTC, SergeAstapov requested changes

2021-12-07 04:19 UTC, SergeAstapov commented on tests/dummy/app/components/my-component.js
> +  constructor() {
@sergeykers lets remove this `constructor` as it does nothing

2021-12-07 04:19 UTC, SergeAstapov commented on tests/dummy/app/templates/infinity-right-left.hbs
> +      &nbsp;
nice catch!

2021-12-07 04:19 UTC, SergeAstapov commented on tests/unit/mixins/in-viewport-test.js
>  import RafPool from 'raf-pool';
@sergeykers I believe this test file needs to be renamed as well as test module because there is no more mixin involved

2021-12-08 14:55 UTC, andrei-sviazhin approved these changes

2021-12-08 14:55 UTC, andrei-sviazhin commented on tests/unit/mixins/in-viewport-test.js
>  import RafPool from 'raf-pool';
@SergeAstapov Name of this test now is `Unit | Mixin | in viewport`, but we've remove `InViewportMixin` from here  and it actually became a test for RafPool package only. Should we keep this test at all?

2021-12-09 05:32 UTC, SergeAstapov approved these changes

2021-12-09 05:36 UTC, SergeAstapov requested changes

2021-12-09 05:36 UTC, SergeAstapov commented on tests/unit/mixins/in-viewport-test.js
>  import RafPool from 'raf-pool';
@sergeykers let's keep the test but rename the file to `tests/unit/raf-pool-test.js` and change the line

```js
module('Unit | Mixin | in viewport', function (hooks) {
```

to

```js
module('Unit | Raf Pool', function (hooks) {
```

2021-12-10 22:18 UTC, merged